### ISSUE TITLE
core.py, line 45  invalid syntax

### ISSUE THREAD

**Issue by nixis-institute** [heroku/django-heroku#23]
I got this is error when run on localhost 
please give resolution to solve it

<img width="960" alt="error" src="https://user-images.githubusercontent.com/41456162/44411418-174d2d00-a584-11e8-9754-b1ca7dd6cbf4.png">

**Comment by edmorley** [comment]
The `django-heroku` package requires Python 3. From the README:

> Django 2.0 is targeted, but older versions of Django should be compatible. Only Python 3 is supported.

However `setup.py` should probably be modified to make this more explicit, by:
* removing the `Python :: 2.*` trove classifiers
* adding a suitable value for `python_requires` (though only read by pip 9+) or else a runtime check ([see here for example implementations](https://python3statement.org/practicalities/))

**Comment by sigmavirus24** [comment]
See also #8
