### ISSUE TITLE
Psycopg2 cannot be installed

### ISSUE THREAD

**Issue by PNjinu** [heroku/django-heroku#47]
So when trying to install django-heroku, the psycopg2 can't be installed.

**Comment by ballin2much** [comment]
Did you find a solution for this?

**Comment by PNjinu** [comment]
@ballin2much Yes. Though it depends with OS being used. Would you please post your error I see if I can help?

**Comment by jonathanstegall** [comment]
@PNjinu do you have a fix for this in OSX? I get the `An error occurred while installing psycopg2==2.8.3` error and it fails to install django-heroku, even though I already have psycopg2-binary installed.
