### ISSUE TITLE
Security issue with ALLOWED_HOSTS

### ISSUE THREAD

**Issue by wowkin2** [heroku/django-heroku#5]
I found that in core module:
[config['ALLOWED_HOSTS'] = ['*']](https://github.com/heroku/django-heroku/blob/master/django_heroku/core.py#L106)
And that is not good for security. You should read domain info somewhere from Heroku or explicitly set from settings.py.

**Comment by kennethreitz** [comment]
no, this is fine on heroku. heroku only allows requests from allowed domains to your application.
